# The Docker image that will be used to build your app
image: alpine:latest
pages:
  script:
    - apk add --update-cache --repository
      http://dl-cdn.alpinelinux.org/alpine/edge/community/ zola
    - zola build
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  tags:
    - ci.inria.fr
    - small
