# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SWEET - Shallow Water Equation Environment for Tests, Awesome!
email: schreiberx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        PDE solver framework for global spectral methods (bi-periodic plane and sphere)

baseurl: "/sweetsite/" # the subpath of your site, e.g. /blog
url: "https://schreiberx.github.io" # the base hostname & protocol for your site
#twitter_username: 
#github_username: 
github_username: schreiberx
git_repo: sweetsite

# Build settings
markdown: kramdown

plugins:
  - jemoji
  - jekyll-relative-links

#theme: jekyll-theme-chirpy
